'''
Descripttion: 
version: 
Author: Hubery-Lee
Date: 2021-08-22 18:28:35
E-mail: hrbeulh@126.com
LastEditors: Hubery-Lee
LastEditTime: 2021-08-22 19:51:29
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(541, 342)
        About.setStyleSheet("#About\n"
"{\n"
"border-image: url(:/images/about_bg.png);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(About)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(About)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Form"))
        self.textBrowser.setHtml(_translate("About", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">关于leeOCR</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    </span><span style=\" font-size:12pt;\">leeOCR是一个文本识别小工具，可实现图片和文字的识别。leeOCR由忽必烈李开发，可通过</span><a href=\"hrbeulh@126.com\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">hrbeulh@126.com</span></a><span style=\" font-size:12pt;\">联系开发人员。此软件的获取途径除上述方法外，可通过一下两种方式获取该工具：1）如下图微信公众号获取；2）通过</span><a href=\"https://github.com/Hubery-Lee/leeOCR\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">https://github.com/Hubery-Lee/leeOCR</span></a></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/scanCode.png\" /></p></body></html>"))
import images_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     About = QtWidgets.QWidget()
#     ui = Ui_About()
#     ui.setupUi(About)
#     About.show()
#     sys.exit(app.exec_())
